SCR_MissionHeaderCombatOps {
 World "{067782A43115BD11}worlds/Mission2.ent"
 m_sName "Operation Allied Hammer. Episode 2"
 m_sAuthor "[REV]Zakat616 [tor]Budda"
 m_sIcon "{81ECED4DC484EF87}UI/Mis2_BCR.edds"
 m_sLoadingScreen "{81ECED4DC484EF87}UI/Mis2_BCR.edds"
 m_sPreviewImage "{81ECED4DC484EF87}UI/Mis2_BCR.edds"
 m_sGameMode "#AR-ServerBrowser_ServerScenario"
 m_iPlayerCount 128
 m_bOverrideScenarioTimeAndWeather 1
 m_iStartingHours 10
 m_aTaskTypesAvailable {
  SCR_ScenarioFrameworkTaskType "{69CD45C2AB88728B}" {
   m_eTypeOfTask DELIVER
  }
  SCR_ScenarioFrameworkTaskType "{69CD45C2AB887207}" {
   m_eTypeOfTask DESTROY
  }
  SCR_ScenarioFrameworkTaskType "{69CD45C2AB887218}" {
   m_eTypeOfTask CLEAR_AREA
  }
  SCR_ScenarioFrameworkTaskType "{69CD45C2AB88721A}" {
   m_eTypeOfTask KILL
  }
  SCR_ScenarioFrameworkTaskType "{69CD45C2AB88721B}" {
   m_eTypeOfTask DEFEND
  }
 }
}