SCR_MissionHeaderCombatOps {
 World "{89979D4ABE36DE46}worlds/Mission1.ent"
 m_sName "Operation Allied Hammer. Episode 1"
 m_sAuthor "[REV]Zakat616 [tor]Budda"
 m_sIcon "{C11CCC6872986DC0}UI/Mis1_BCR.edds"
 m_sLoadingScreen "{C11CCC6872986DC0}UI/Mis1_BCR.edds"
 m_sPreviewImage "{C11CCC6872986DC0}UI/Mis1_BCR.edds"
 m_sGameMode "#AR-ServerBrowser_ServerScenario"
 m_iPlayerCount 128
 m_bOverrideScenarioTimeAndWeather 1
 m_iStartingHours 5
 m_iStartingMinutes 30
 m_aTaskTypesAvailable {
  SCR_ScenarioFrameworkTaskType "{6916A594A4A14D78}" {
   m_eTypeOfTask DELIVER
  }
  SCR_ScenarioFrameworkTaskType "{6916A594A4A14D45}" {
   m_eTypeOfTask DESTROY
  }
  SCR_ScenarioFrameworkTaskType "{6916A594A4A14D47}" {
   m_eTypeOfTask CLEAR_AREA
  }
  SCR_ScenarioFrameworkTaskType "{6916A594A4A12918}" {
   m_eTypeOfTask KILL
  }
  SCR_ScenarioFrameworkTaskType "{6916A594A4A12907}" {
   m_eTypeOfTask DEFEND
  }
 }
}