SCR_MissionHeaderCombatOps {
 World "{12F41F858FA4C4CF}worlds/Mission3remastered.ent"
 m_sName "Operation Allied Hammer. Episode 3"
 m_sAuthor "[REV]Zakat616 "
 m_sIcon "{7FECAD0831D683CB}UI/Mis3_BCR.edds"
 m_sLoadingScreen "{7FECAD0831D683CB}UI/Mis3_BCR.edds"
 m_sPreviewImage "{7FECAD0831D683CB}UI/Mis3_BCR.edds"
 m_sGameMode "#AR-ServerBrowser_ServerScenario"
 m_iPlayerCount 128
 m_bOverrideScenarioTimeAndWeather 1
 m_iStartingHours 18
 m_iStartingMinutes 30
 m_aTaskTypesAvailable {
  SCR_ScenarioFrameworkTaskType "{6A60B35B5ED04932}" {
   m_eTypeOfTask DELIVER
  }
  SCR_ScenarioFrameworkTaskType "{6A60B35B5ED04954}" {
   m_eTypeOfTask DESTROY
  }
  SCR_ScenarioFrameworkTaskType "{6A60B35B5ED04956}" {
   m_eTypeOfTask CLEAR_AREA
  }
  SCR_ScenarioFrameworkTaskType "{6A60B35B5ED04957}" {
   m_eTypeOfTask KILL
  }
  SCR_ScenarioFrameworkTaskType "{6A60B35B5ED04AA8}" {
   m_eTypeOfTask DEFEND
  }
 }
}